<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Pigeon.Persistence.Sqlite/Pigeon.Persistence.Sqlite.csproj" />
    <ProjectReference Include="../../src/Pigeon.Simulation/Pigeon.Simulation.csproj" />
  </ItemGroup>

</Project>
